name: Build Executables

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main

    - uses: actions/upload-artifact@v4
      with:
        name: name-of-artifact
        path: src/dist/windows
